<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $skillsList = [

            "Communication Skills",
            "Critical Thinking",
            "Problem Solving",
            "Creativity",
            "Teamwork",
            "Leadership",
            "Adaptability",
            "Time Management",
            "Emotional Intelligence",
            "Decision Making",
            "Analytical Skills",
            "Project Management",
            "Collaboration",
            "Negotiation",
            "Conflict Resolution",
            "Networking",
            "Presentation Skills",
            "Strategic Planning",
            "Research",
            "Data Analysis",
            "Digital Literacy",
            "Risk Management",
            "Coaching/Mentoring",
            "Learning Agility",
            "Crisis Management",
            "Health and Wellness",
            "Cultural Competence",
            "Active Listening",
            "Empathy",
            "Flexibility",
            "Innovation",
            "Multitasking",
            "Attention to Detail",
            "Work-Life Balance",
            "Stress Management",
            "Self-Motivation",
            "Goal Setting",
            "Performance Management",
            "Change Management",
            "Team Building",
            "Cross-functional Collaboration",
            "Python",
            "Java",
            "JavaScript",
            "C++",
            "Ruby",
            "PHP",
            "Swift",
            "Kotlin",
            "TypeScript",
            "HTML/CSS",
            "C",
            "C#",
            "Go",
            "Rust",
            "Scala",
            "Perl",
            "MATLAB",
            "R",
            "Objective-C",
            "Dart",
            "Assembly Language",
            "COBOL",
            "Fortran",
            "Haskell",
            "Lua",
            "Shell Scripting",
            "PowerShell",
            "VBA",
            "SQL",
            "PL/SQL",
            "T-SQL",
            "NoSQL",
            "GraphQL",
            "YAML",
            "JSON",
            "XML",
            "Markdown",
            "React.js",
            "Angular",
            "Vue.js",
            "Node.js",
            "Django",
            "Flask",
            "Ruby on Rails",
            "ASP.NET",
            "Laravel",
            "Express.js",
            "Spring Boot",
            "Symfony",
            "CodeIgniter",
            "Zend Framework",
            "CakePHP",
            "FastAPI",
            "Tornado",
            "Sinatra",
            "Play Framework",
            "Ember.js",
            "Backbone.js",
            "Svelte",
            "Next.js",
            "Nuxt.js",
            "Gatsby",
            "Hugo",
            "Jekyll",
            "WordPress Development",
            "Drupal Development",
            "Magento Development",
            "Shopify Development",
            "WooCommerce",
            "REST API Development",
            "SOAP API Development",
            "Microservices Architecture",
            "Serverless Computing",
            "JAMstack",
            "Progressive Web Apps (PWA)",
            "Single Page Applications (SPA)",
            "Cross-Origin Resource Sharing (CORS)",
            "OAuth",
            "JWT Authentication",
            "Session Management",
            "Cookie Management",
            "HTTPS/SSL",
            "Web Security",
            "OWASP Top 10",
            "XSS Prevention",
            "CSRF Protection",
            "SQL Injection Prevention",
            "Content Security Policy (CSP)",
            "Web Performance Optimization",
            "Caching Strategies",
            "CDN Implementation",
            "Load Balancing",
            "Web Accessibility (WCAG)",
            "Responsive Web Design",
            "Mobile-First Design",
            "Browser Compatibility",
            "Cross-Browser Testing",
            "React Native",
            "Flutter",
            "Xamarin",
            "Swift (iOS)",
            "Kotlin (Android)",
            "Java (Android)",
            "Objective-C (iOS)",
            "Ionic",
            "PhoneGap/Cordova",
            "Unity (Mobile Games)",
            "Unreal Engine (Mobile)",
            "ARKit",
            "ARCore",
            "Core Data",
            "Room Database",
            "SQLite",
            "Realm Database",
            "Firebase",
            "Push Notifications",
            "In-App Purchases",
            "App Store Optimization (ASO)",
            "Mobile UI/UX Design",
            "Mobile Testing",
            "TestFlight",
            "Google Play Console",
            "App Distribution",
            "Mobile Analytics",
            "Crash Reporting",
            "Performance Monitoring",
            "AWS (Amazon Web Services)",
            "Azure",
            "Google Cloud Platform",
            "IBM Cloud",
            "Oracle Cloud",
            "DigitalOcean",
            "Linode",
            "Vultr",
            "Heroku",
            "Vercel",
            "Netlify",
            "AWS EC2",
            "AWS S3",
            "AWS Lambda",
            "AWS RDS",
            "AWS DynamoDB",
            "AWS CloudFormation",
            "AWS CloudWatch",
            "AWS IAM",
            "AWS VPC",
            "AWS API Gateway",
            "Azure Functions",
            "Azure SQL Database",
            "Azure Cosmos DB",
            "Azure Active Directory",
            "Azure DevOps",
            "Google Compute Engine",
            "Google Cloud Storage",
            "Google Cloud Functions",
            "Google BigQuery",
            "Google Cloud SQL",
            "Google Kubernetes Engine",
            "Cloud Architecture",
            "Cloud Migration",
            "Cloud Security",
            "Cloud Cost Optimization",
            "Multi-Cloud Strategy",
            "Hybrid Cloud",
            "Cloud Monitoring",
            "Cloud Backup",
            "Disaster Recovery",
            "Infrastructure as Code (IaC)",
            "Terraform",
            "CloudFormation",
            "Ansible",
            "Puppet",
            "Chef",
            "SaltStack",
            "Kubernetes",
            "Docker",
            "Docker Compose",
            "Docker Swarm",
            "OpenShift",
            "Rancher",
            "Helm",
            "Jenkins",
            "GitLab CI/CD",
            "GitHub Actions",
            "Azure DevOps",
            "CircleCI",
            "Travis CI",
            "TeamCity",
            "Bamboo",
            "Continuous Integration (CI)",
            "Continuous Deployment (CD)",
            "Infrastructure Monitoring",
            "Application Monitoring",
            "Log Management",
            "ELK Stack (Elasticsearch, Logstash, Kibana)",
            "Splunk",
            "Datadog",
            "New Relic",
            "Prometheus",
            "Grafana",
            "Nagios",
            "Zabbix",
            "PagerDuty",
            "Configuration Management",
            "Version Control",
            "Git",
            "SVN",
            "Mercurial",
            "Perforce",
            "GitFlow",
            "Branching Strategies",
            "Code Review",
            "Pull Requests",
            "Merge Conflicts Resolution",
            "MySQL",
            "PostgreSQL",
            "MongoDB",
            "Redis",
            "Elasticsearch",
            "Cassandra",
            "Neo4j",
            "InfluxDB",
            "CouchDB",
            "Amazon DynamoDB",
            "Oracle Database",
            "Microsoft SQL Server",
            "SQLite",
            "MariaDB",
            "Firebase Firestore",
            "Apache HBase",
            "Apache CouchDB",
            "RavenDB",
            "ArangoDB",
            "FaunaDB",
            "Supabase",
            "PlanetScale",
            "Database Design",
            "Database Optimization",
            "Query Optimization",
            "Database Administration",
            "Data Warehousing",
            "ETL Processes",
            "Data Pipeline",
            "Data Migration",
            "Database Security",
            "Backup and Recovery",
            "Replication",
            "Sharding",
            "Indexing Strategies",
            "ACID Properties",
            "CAP Theorem",
            "Data Modeling",
            "Normalization",
            "Denormalization",
            "Cybersecurity",
            "Penetration Testing",
            "Ethical Hacking",
            "Vulnerability Assessment",
            "Security Auditing",
            "Incident Response",
            "Malware Analysis",
            "Digital Forensics",
            "Network Security",
            "Application Security",
            "Cloud Security",
            "Mobile Security",
            "IoT Security",
            "Cryptography",
            "PKI (Public Key Infrastructure)",
            "SSL/TLS",
            "VPN",
            "Firewall Configuration",
            "Intrusion Detection Systems (IDS)",
            "Intrusion Prevention Systems (IPS)",
            "SIEM (Security Information and Event Management)",
            "SOC (Security Operations Center)",
            "Risk Assessment",
            "Compliance (GDPR, HIPAA, SOX)",
            "ISO 27001",
            "NIST Framework",
            "Security Awareness Training",
            "Phishing Detection",
            "Social Engineering",
            "Zero Trust Architecture",
            "Multi-Factor Authentication (MFA)",
            "Identity and Access Management (IAM)",
            "Privileged Access Management (PAM)",
            "Data Loss Prevention (DLP)",
            "Endpoint Security",
            "Anti-virus/Anti-malware",
            "Backup Security",
            "Business Continuity Planning",
            "Security Policy Development",
            "Threat Intelligence",
            "OSINT (Open Source Intelligence)",
            "Red Team Operations",
            "Blue Team Operations",
            "Purple Team Operations",
            "TensorFlow",
            "PyTorch",
            "scikit-learn",
            "Keras",
            "SAS",
            "SPSS",
            "Pandas",
            "NumPy",
            "Matplotlib",
            "Seaborn",
            "Plotly",
            "D3.js",
            "Tableau",
            "Power BI",
            "Qlik Sense",
            "Apache Spark",
            "Hadoop",
            "Hive",
            "Pig",
            "HBase",
            "Kafka",
            "Apache Airflow",
            "Apache NiFi",
            "Jupyter Notebooks",
            "Google Colab",
            "Azure Machine Learning",
            "AWS SageMaker",
            "Google AI Platform",
            "MLflow",
            "Kubeflow",
            "Docker for ML",
            "Model Deployment",
            "Model Monitoring",
            "A/B Testing",
            "Statistical Analysis",
            "Hypothesis Testing",
            "Regression Analysis",
            "Classification",
            "Clustering",
            "Natural Language Processing (NLP)",
            "Computer Vision",
            "Deep Learning",
            "Neural Networks",
            "Convolutional Neural Networks (CNN)",
            "Recurrent Neural Networks (RNN)",
            "LSTM",
            "GAN (Generative Adversarial Networks)",
            "Transformer Models",
            "BERT",
            "GPT",
            "Reinforcement Learning",
            "Feature Engineering",
            "Data Preprocessing",
            "Data Cleaning",
            "Data Visualization",
            "Exploratory Data Analysis (EDA)",
            "Time Series Analysis",
            "Forecasting",
            "Recommendation Systems",
            "Anomaly Detection",
            "Sentiment Analysis",
            "Image Recognition",
            "Speech Recognition",
            "Chatbot Development",
            "AutoML",
            "Model Interpretability",
            "Bias Detection",
            "Fairness in ML",
            "Ethics in AI",
            "Network Administration",
            "System Administration",
            "Linux Administration",
            "Windows Server Administration",
            "Active Directory",
            "LDAP",
            "DNS Management",
            "DHCP Configuration",
            "TCP/IP",
            "Subnetting",
            "VLAN Configuration",
            "Routing Protocols",
            "BGP",
            "OSPF",
            "EIGRP",
            "Load Balancers",
            "Proxy Servers",
            "Web Servers (Apache, Nginx)",
            "Mail Servers",
            "FTP Servers",
            "SSH",
            "Telnet",
            "SNMP",
            "Network Troubleshooting",
            "Packet Analysis",
            "Wireshark",
            "Network Monitoring",
            "Bandwidth Management",
            "Quality of Service (QoS)",
            "Network Security",
            "Wireless Networking",
            "WiFi Configuration",
            "Bluetooth",
            "Network Hardware",
            "Switches",
            "Routers",
            "Firewalls",
            "Access Points",
            "Network Cables",
            "Fiber Optics",
            "Network Design",
            "Network Documentation",
            "Capacity Planning",
            "Performance Tuning",
            "Virtualization",
            "VMware",
            "Hyper-V",
            "VirtualBox",
            "KVM",
            "Xen",
            "Container Orchestration",
            "Service Mesh",
            "Istio",
            "Consul",
            "Envoy Proxy",
            "Financial Literacy",
            "Marketing Strategy",
            "Sales",
            "Customer Service",
            "Quality Assurance",
            "Supply Chain Management",
            "Public Relations",
            "Social Media Management",
            "SEO (Search Engine Optimization)",
            "SEM (Search Engine Marketing)",
            "Content Marketing",
            "Email Marketing",
            "Affiliate Marketing",
            "Influencer Marketing",
            "Brand Management",
            "Market Research",
            "Customer Relationship Management (CRM)",
            "Salesforce",
            "HubSpot",
            "Marketo",
            "Mailchimp",
            "Google Analytics",
            "Google Ads",
            "Facebook Ads",
            "LinkedIn Ads",
            "Twitter Ads",
            "Amazon Advertising",
            "E-commerce",
            "Conversion Rate Optimization (CRO)",
            "User Experience (UX) Design",
            "User Interface (UI) Design",
            "Design Thinking",
            "Prototyping",
            "Wireframing",
            "User Research",
            "Usability Testing",
            "Information Architecture",
            "Interaction Design",
            "Visual Design",
            "Graphic Design",
            "Web Design",
            "Mobile App Design",
            "Product Management",
            "Product Strategy",
            "Product Roadmap",
            "Agile Methodologies",
            "Scrum",
            "Kanban",
            "Lean Startup",
            "Six Sigma",
            "ITIL",
            "Prince2",
            "PMP Certification",
            "Business Analysis",
            "Requirements Gathering",
            "Process Improvement",
            "Workflow Optimization",
            "Business Intelligence",
            "Data Governance",
            "Vendor Management",
            "Contract Negotiation",
            "Budget Management",
            "Cost Analysis",
            "ROI Analysis",
            "KPI Development",
            "Performance Metrics",
            "Reporting",
            "Documentation",
            "Technical Writing",
            "Training and Development",
            "Knowledge Management",
            "Stakeholder Management",
            "Client Relations",
            "Customer Success",
            "Account Management",
            "Business Development",
            "Partnership Development",
            "Mergers and Acquisitions",
            "Due Diligence",
            "Compliance Management",
            "Audit Preparation",
            "Legal Knowledge",
            "Intellectual Property",
            "Data Privacy",
            "GDPR Compliance",
            "CCPA Compliance",
            "HIPAA Compliance",
            "Adobe Creative Suite (Photoshop, Illustrator, InDesign)",
            "Sketch",
            "Canva",
            "Adobe Premiere Pro",
            "Final Cut Pro",
            "DaVinci Resolve",
            "Figma",
            "Adobe XD",
            "InVision",
            "Marvel",
            "Zeplin",
            "Abstract",
            "Principle",
            "Framer",
            "Adobe After Effects",
            "Adobe Lightroom",
            "Adobe Audition",
            "Logic Pro",
            "Pro Tools",
            "Ableton Live",
            "Blender",
            "Maya",
            "3ds Max",
            "Cinema 4D",
            "Unity",
            "Unreal Engine",
            "SketchUp",
            "AutoCAD",
            "SolidWorks",
            "Fusion 360",
            "KeyShot",
            "Substance Painter",
            "ZBrush",
            "Houdini",
            "Nuke",
            "Davinci Resolve",
            "Avid Media Composer",
            "Adobe Animate",
            "Toon Boom Harmony",
            "Procreate",
            "Affinity Designer",
            "Affinity Photo",
            "CorelDRAW",
            "GIMP",
            "Inkscape",
            "Krita",
            "Content Writing",
            "Technical Writing",
            "Copywriting",
            "Blogging",
            "Journalism",
            "Editing",
            "Proofreading",
            "Translation",
            "Foreign Language Proficiency",
            "Public Speaking",
            "Podcasting",
            "Video Production",
            "Audio Production",
            "Photography",
            "Videography",
            "Live Streaming",
            "YouTube Management",
            "Twitch Streaming",
            "Voice Acting",
            "Music Production",
            "Sound Design",
            "3D Modeling",
            "3D Animation",
            "VFX (Visual Effects)",
            "Motion Graphics",
            "Game Development",
            "Game Design",
            "Level Design",
            "Character Design",
            "Concept Art",
            "Storyboarding",
            "Script Writing",
            "Creative Writing",
            "Screenwriting",
            "Novel Writing",
            "Poetry",
            "Grant Writing",
            "Proposal Writing",
            "Academic Writing",
            "Research Writing",
            "Medical Writing",
            "Legal Writing",
            "Business Writing",
            "Email Writing",
            "Social Media Writing",
            "Press Release Writing",
            "Marketing Copy",
            "Sales Copy",
            "Web Copy",
            "SEO Writing",
            "Content Strategy",
            "Content Planning",
            "Editorial Calendar",
            "Content Management Systems (CMS)",
            "WordPress",
            "Drupal",
            "Joomla",
            "Webflow",
            "Squarespace",
            "Wix",
            "Shopify",
            "Magento",
            "PrestaShop",
            "OpenCart",
            "BigCommerce",
            "WooCommerce",
            "Email Automation",
            "Marketing Automation",
            "Customer Journey Mapping",
            "Conversion Funnels",
            "Landing Page Optimization",
            "Growth Hacking",
            "Viral Marketing",
            "Guerrilla Marketing",
            "Event Marketing",
            "Trade Show Management",
            "Conference Speaking",
            "Workshop Facilitation",
            "Training Delivery",
            "Curriculum Development",
            "E-learning Development",
            "LMS Administration",
            "Instructional Design",
            "Adult Learning Principles",
            "Educational Technology",
            "Distance Learning",
            "Virtual Training",
            "Webinar Hosting",
            "Online Course Creation",
            "Video Tutorials",
            "Screen Recording",
            "Live Demonstrations",
            "Technical Support",
            "Customer Support",
            "Help Desk Management",
            "Ticketing Systems",
            "Remote Support",
            "Hardware Troubleshooting",
            "Software Troubleshooting",
            "Mobile Device Management",
            "Asset Management",
            "Inventory Management",
            "Procurement",
            "Vendor Relations",
            "Service Level Agreements (SLA)",
            "Change Management",
            "Incident Management",
            "Problem Management",
            "Release Management",
            "Configuration Management",
            "Knowledge Base Management",
            "FAQ Development",
            "User Manual Writing",
            "API Documentation",
            "Code Documentation",
            "Software Documentation",
            "System Documentation",
            "Process Documentation",
            "Policy Development",
            "Procedure Writing",
            "Standard Operating Procedures (SOP)",
            "Quality Control",
            "Quality Management",
            "ISO Standards",
            "Testing Methodologies",
            "Test Case Development",
            "Test Automation",
            "Performance Testing",
            "Load Testing",
            "Security Testing",
            "Usability Testing",
            "Accessibility Testing",
            "Cross-platform Testing",
            "Regression Testing",
            "User Acceptance Testing (UAT)",
            "Beta Testing",
            "Bug Tracking",
            "Defect Management",
            "Code Review",
            "Peer Review",
            "Technical Interview",
            "Code Challenge",
            "Algorithm Design",
            "Data Structures",
            "Software Architecture",
            "Design Patterns",
            "Refactoring",
            "Code Optimization",
            "Performance Optimization",
            "Memory Management",
            "Garbage Collection",
            "Concurrent Programming",
            "Parallel Programming",
            "Distributed Systems",
            "Microservices",
            "Event-Driven Architecture",
            "Domain-Driven Design (DDD)",
            "Test-Driven Development (TDD)",
            "Behavior-Driven Development (BDD)",
            "Continuous Learning",
            "Industry Research",
            "Technology Trends",
            "Innovation Management",
            "Digital Transformation",
            "Technology Adoption",
            "Proof of Concept (POC)",
            "Minimum Viable Product (MVP)",
            "Rapid Prototyping",
            "Iterative Development",
            "Agile Testing",
            "DevSecOps",
            "Site Reliability Engineering (SRE)",
            "Platform Engineering",
            "Data Engineering",
            "MLOps",
            "AIOps",
            "GitOps",
            "NoOps",
            "ChatOps",
            "FinOps",
            "Green Computing",
            "Sustainable Technology",
            "Digital Ethics",
            "Technology Law",
            "Patent Research",
            "Open Source Contribution",
            "Community Building",
            "Technical Mentoring",
            "Code Mentoring",
            "Career Development",
            "Professional Development",
            "Certification Management",
            "Skill Assessment",
            "Competency Mapping",
            "Learning Path Development",
            "Technology Roadmap",
            "Architecture Review",
            "Technology Stack Selection",
            "Tool Evaluation",
            "Vendor Evaluation",
            "Technology Consulting",
            "Digital Strategy",
            "IT Strategy",
            "Technology Planning",
            "Capacity Planning",
            "Scalability Planning",
            "Disaster Recovery Planning",
            "Business Continuity",
            "Emergency Response",
            "Crisis Communication"
        ];

        foreach($skillsList as $skill) {
            $data = new Skill();
            $data->name = $skill;
            $data->save();
        }
    }
}
